const categories = [
  {
    id: 1,
    title: "Arts & Music",
    slug: "arts-music",
    subcategories: ["Art History", "Calligraphy", "Drawing", "Fashion", "Film"],
  },
  {
    id:2,
    title: "Biographies",
    slug: "biographies",
    subcategories: [
      "Ethnic & Cultural",
      "Europe",
      "Historical",
      "Leaders & Notable People",
      "Military",
    ],
  },
  {
    id:3,
    title: "Business",
    slug: "business",
    subcategories: [
      "Careers",
      "Economics",
      "Finance",
      "Industries",
      "International",
    ],
  },
  {
    id:4,
    title: "Comics",
    slug: "comics",
    subcategories: [
      "Comic Books",
      "Comic Strips",
      "Dark Horse",
      "DC Comics",
      "Fantasy",
    ],
  },
  {
    id:5,
    title: "Computers & Tech",
    slug: "computers-tech",
    subcategories: [
      "Apple",
      "CAD",
      "Certification",
      "Computer Science",
      "Databases",
    ],
  },
  {
    id:6,
    title: "Cooking",
    slug: "cooking",
    subcategories: ["Asian", "Baking", "BBQ", "Culinary Arts", "Desserts"],
  },
  {
    id:7,
    title: "Edu & Reference",
    slug: "edu-reference",
    subcategories: [
      "Almanacs & Yearbooks",
      "Atlases & Maps",
      "Catalogs",
      "Colleges",
      "Continuing Education",
    ],
  },
  {
    id:8,
    title: "Entertainment",
    slug: "entertainment",
    subcategories: [
      "Brain Teasers",
      "Entertainers",
      "Games",
      "Humor",
      "Movies",
    ],
  },
  {
    id:9,
    title: "Health & Fitness",
    slug: "health-fitness",
    subcategories: [
      "Aging",
      "Alternative Medicine",
      "Beauty, Grooming & Style",
      "Children's Health",
      "Disease & Ailments",
    ],
  },
  {
    id:10,
    title: "History",
    slug: "history",
    subcategories: ["African", "Ancient", "Asian", "Black History", "Canadian"],
  },
  {
    id:11,
    title: "Hobbies & Crafts",
    slug: "hobbies-crafts",
    subcategories: [
      "Antiques",
      "Clay",
      "Collecting",
      "Fashion",
      "Jewelry Making",
    ],
  },
  {
    id:12,
    title: "Home & Garden",
    slug: "home-garden",
    subcategories: [
      "Architecture",
      "Flowers",
      "Fruit",
      "Home Decorating",
      "Home Improvement",
    ],
  },
  {
    id:13,
    title: "Horror",
    slug: "horror",
    subcategories: [
      "Ghosts",
      "Paranormal",
      "Supernatural",
      "Vampires",
      "Zombies",
    ],
  },
  {
    id:14,
    title: "Kids",
    slug: "kids",
    subcategories: [
      "Action & Adventure",
      "Activities, Crafts & Games",
      "Activity Books",
      "Animals",
    ],
  },
  {
    id:15,
    title: "Literature & Fiction",
    slug: "literature-fiction",
    subcategories: [
      "Anthologies",
      "Classics",
      "Contemporary",
      "Foreign Language",
      "Genre Fiction",
    ],
  },
  {
    id:16,
    title: "Medical",
    slug: "medical",
    subcategories: [
      "Administration",
      "Allied Health",
      "Basic Sciences",
      "Clinical",
      "Dentistry",
    ],
  },
  {
    id:17,
    title: "Mysteries",
    slug: "mysteries",
    subcategories: [
      "Conspiracy",
      "Crime",
      "Detective",
      "Mysteries",
      "Suspense",
    ],
  },
  {
    id:18,
    title: "Parenting",
    slug: "parenting",
    subcategories: [
      "Adoption",
      "Aging Parents",
      "Child Care",
      "Family Activities",
      "Family Health",
    ],
  },
  {
    id:19,
    title: "Religion",
    slug: "religion",
    subcategories: [
      "Agnosticism",
      "Astrology",
      "Atheism",
      "Buddhism",
      "Christian",
    ],
  },
  {
    id:20,
    title: "Romance",
    slug: "romance",
    subcategories: [
      "Anthologies",
      "Contemporary",
      "Erotica",
      "Fantasy",
      "Gothic",
    ],
  },
  {
    id:21,
    title: "Sci-Fi & Fantasy",
    slug: "sci-fi-fantasy",
    subcategories: [
      "Action",
      "Anthologies",
      "Coming of Age",
      "Dark Fantasy",
      "Fantasy",
    ],
  },
  {
    id:22,
    title: "Science & Math",
    slug: "science-math",
    subcategories: [
      "Agricultural Sciences",
      "Anatomy",
      "Animals",
      "Astronomy",
      "Biology",
    ],
  },
  {
    id:23,
    title: "Self-Help",
    slug: "self-help",
    subcategories: [
      "Abuse",
      "Addictions",
      "Anger Management",
      "Anxieties & Phobias",
      "Creativity",
    ],
  },
  {
    id:24,
    title: "Social Sciences",
    slug: "social-sciences",
    subcategories: [
      "Anarchy",
      "Canadian Politics",
      "Civil Rights",
      "Comparative Politics",
      "Cultural",
    ],
  },
  {
    id:25,
    title: "Sports",
    slug: "sports",
    subcategories: [
      "Baseball & Softball",
      "Basketball",
      "Boating & Sailing",
      "Camping",
      "Extreme Sports",
    ],
  },
  {
    id:26,
    title: "Travel",
    slug: "travel",
    subcategories: ["Africa", "Asia", "Canada", "Caribbean", "Europe"],
  },
  {
    id:27,
    title: "True Crime",
    slug: "true-crime",
    subcategories: [
      "Criminal Law",
      "Famous Criminals",
      "Murder & Mayhem",
      "Organized Crime",
      "Serial Killers",
    ],
  },
  {
    id:28,
    title: "Westerns",
    slug: "westerns",
    subcategories: ["Native American"],
  },
  // {
  //   title: "Offers",
  //   slug: "offers",
  //   subcategories: ["ReadingRewards", "Teacher Discount", "Tell-a-Friend", "Gift Cards", "Free Shipping"],
  // },
  // {
  //   title: "Special Editions",
  //   slug: "special-editions",
  //   subcategories: ["Large Print", "Collectibles", "First Editions", "Signed Copies"],
  // },
];

export default categories;
