import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import toast, { Toaster } from "react-hot-toast";

import AuthProvider from "./context/auth";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BookCrafters",
  description: "Generated by Mahbub Ahmed Turza",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={inter.className}
        >
          <link rel="icon" href="/home.png" sizes="any" />
          <Navbar />
          <div className="min-h-screen">
          {children}
          </div>
          <Footer/>
          <Toaster />
        </body>
      </html>
    </AuthProvider>
  );
}
